# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven and push to Azure Container registry

on:
  workflow_dispatch: # Manual trigger
  push:
    branches: [ main ]
    paths: 'src/**'
  pull_request:
    branches: [ main ]
    paths: 'src/**'

env:
  APP_VERSION: ${{ github.sha }}

jobs:
  push: 
    runs-on: ubuntu-latest

    strategy:
      matrix: { 
                dir: [  "spring-petclinic-customers-service",
                        "spring-petclinic-discovery-server",
                        "spring-petclinic-vets-service",
                        "spring-petclinic-visits-service",
                        "spring-petclinic-api-gateway",
                        "spring-petclinic-admin-server",
                        "spring-petclinic-config-server"
                     ] 
              }
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file src/pom.xml
    - name: Log into registry
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.ACR_ENDPOINT }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    - name: Build and push Docker image for 
      uses: docker/build-push-action@v2
      with:
        context: src/${{ matrix.dir }}
        push: true
        tags: ${{ secrets.ACR_ENDPOINT}}/${{ matrix.dir }}:${{ env.APP_VERSION}}
        build-args: |
          ARTIFACT_NAME=target/${{ matrix.dir }}-*.jar
  deploy:
    needs: push
    runs-on: ubuntu-latest
    strategy:
      matrix: { 
                dir: [  "spring-petclinic-customers-service",
                        "spring-petclinic-discovery-server",
                        "spring-petclinic-vets-service",
                        "spring-petclinic-visits-service",
                        "spring-petclinic-api-gateway",
                        "spring-petclinic-admin-server",
                        "spring-petclinic-config-server"
                     ] 
              }
    steps:
      - uses: actions/checkout@v2
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
      - name: Apply application.yaml manifest
        run: |
          - name: Apply application.yaml manifest
            run: |
              sed -i 's/#image#/${{ secrets.ACR_ENDPOINT}}\/${{ matrix.dir }}:${{ env.APP_VERSION}}/g' src/${{ matrix.dir }}/k8s/application.yaml
              sed -i 's/#appname#/${{ matrix.dir }}/g' src/${{ matrix.dir }}/k8s/application.yaml
              kubectl apply -f src/${{ matrix.dir }}/k8s/application.yaml
